import Image from "next/image";
import Link from "next/link";

const features = [
    {
        headline: "Boost Sales",
        content: `Stunning product shoots, carefully crafted by our AI, entice customers towards your product like never before. These shoots have a captivating appeal that grabs attention and drives your product off the shelves. Elevate your sales strategy, and watch as product orders keep flowing in.`,
        image: "/necklace",
    },
    {
        headline: "Get Instant Results",
        content: `Get results instantly in a matter of seconds. Don't like the result? Just click the button again to generate new product shoots effortlessly and promptly. Our lightning-fast AI-powered system ensures you don't waste precious time waiting for your visuals, putting you ahead in your marketing game.`,
        image: "/result-2",
    },
    {
        headline: "High Quality Photos",
        content: `Product images generated are not only delivered swiftly but also boast high resolutions and exceptional quality. You can confidently use them for your e-commerce store, social media platforms, or any other marketing channels, knowing they'll catch eyes and captivate potential customers with their impeccable clarity and sharpness.`,
        image: "/result-1",
    },
    {
        headline: "Value for Money",
        content: `Invest in our AI-powered product shoots and witness exceptional quality without breaking the bank. Get high-quality product shoots for a fraction of the cost of hiring a professional photographer. Save a significant amount of money and time, allowing you to allocate resources elsewhere while reaping the benefits of top-notch product visuals.`,
        image: "/result-4",
    },
    {
        headline: "Endless Customization",
        content: `Tailor the product shoots generated by our AI to suit your unique preferences and branding. With endless customization options, you have the creative freedom to change the background, tweak shadows, adjust lighting, and more. Personalize each visual to align perfectly with your brand's aesthetic, ensuring your product stands out in a crowded market.`,
        image: "/result-6",
    },
    {
        headline: "Full Ownership",
        content: `Rest assured, you retain complete ownership of the product shoots generated by our AI. Utilize them across your e-commerce store, social media platforms, advertisements, or any marketing medium of your choice without any need for attribution. The visuals are yours to deploy as you see fit, empowering you to showcase your products in the best light without any restrictions or obligations.`,
        image: "/result-5",
    },
];

export function FeaturesSection() {
    return (
        <section
            id="features"
            aria-label="Why should you use our product"
            className=""
        >
            <div className="mx-auto px-4 sm:px-6 lg:px-8">
                <div className="mx-auto text-left md:text-center">
                    <h1 className="mx-auto max-w-4xl text-4xl font-bold tracking-normalanimate-text-rainbow bg-gradient-to-r from-teal-500 via-purple-500 to-orange-500 bg-clip-text text-transparent sm:text-6xl">
                        Endless Benefits
                    </h1>
                    <p className="mx-auto mt-6 max-w-xl text-lg pb-8 md:pb-4 text-slate-700 leading-7">
                        Use the power of AI to create stunning, eye-catching
                        product images effortlessly. Our platform offers a wide
                        range of benefits to help you showcase your products in
                        the best possible light.
                    </p>
                    <div className="md:space-y-12">
                        {features.map((feature, index) => {
                            return (
                                <div
                                    key={index}
                                    className="flex md:flex-row flex-col justify-between items-center md:space-y-12 mt-4 md:mt-0"
                                >
                                    {index % 2 == 0 && (
                                        <div className="hidden invisible md:visible flex-col md:flex md:text-left text-slate-900 mr-6">
                                            <div className="max-w-max text-2xl font-bold tracking-normal animate-text-rainbow bg-gradient-to-r from-teal-500 via-purple-500 to-orange-500 bg-clip-text text-transparent sm:text-4xl mb-4">
                                                {feature.headline}
                                            </div>
                                            <div className="text-xl max-w-prose">
                                                {feature.content}
                                            </div>
                                            <Link
                                                className="bg-black rounded-xl w-1/2 self-center md:self-start mt-8 text-center text-white font-medium px-4 py-3 hover:bg-black/80"
                                                href="/create"
                                            >
                                                Get Started With Your First
                                                Shoot
                                            </Link>
                                        </div>
                                    )}
                                    <Image
                                        alt="Product Shoot Image"
                                        width={400}
                                        height={400}
                                        src={feature.image + ".jpg"}
                                        className="w-100 h-100 rounded-2xl md:mt-2"
                                    />
                                    {
                                        <div className="md:hidden md:invisible flex flex-col text-slate-900 my-8">
                                            <div className="max-w-max font-display text-2xl font-bold tracking-normal animate-text-rainbow bg-gradient-to-r from-teal-500 via-purple-500 to-orange-500 bg-clip-text text-transparent sm:text-4xl mb-4">
                                                {feature.headline}
                                            </div>
                                            <div className="text-xl max-w-prose mb-8">
                                                {feature.content}
                                            </div>
                                            <Link
                                                className="bg-black rounded-xl md:self-start text-center text-white font-medium px-6 py-4 mb-4 hover:bg-black/80"
                                                href="/create"
                                            >
                                                Get Started With Your First
                                                Shoot
                                            </Link>
                                        </div>
                                    }
                                    {index % 2 == 1 && (
                                        <div className="hidden invisible md:visible flex-col md:flex md:text-left text-slate-900 ml-6">
                                            <div className="max-w-max font-display text-2xl font-bold tracking-normal animate-text-rainbow bg-gradient-to-r from-teal-500 via-purple-500 to-orange-500 bg-clip-text text-transparent inline-block sm:text-4xl mb-4">
                                                {feature.headline}
                                            </div>
                                            <div className="text-xl max-w-prose">
                                                {feature.content}
                                            </div>
                                            <Link
                                                className="bg-black rounded-xl w-1/2 self-start mt-8 text-center text-white font-medium px-4 py-3 hover:bg-black/80"
                                                href="/create"
                                            >
                                                Get Started With Your First
                                                Shoot
                                            </Link>
                                        </div>
                                    )}
                                </div>
                            );
                        })}
                    </div>
                </div>
            </div>
        </section>
    );
}
