import Image from "next/image";

const features = [
    {
        headline: "Get Instant Results",
        content: `Get results instantly in a matter of seconds. Don't like the result? Just click the button again to generate new product shoots effortlessly and promptly. Our lightning-fast AI-powered system ensures you don't waste precious time waiting for your visuals, putting you ahead in your marketing game.`,
        image: "/result-2",
    },
    {
        headline: "High Quality Photos",
        content: `Product images generated are not only delivered swiftly but also boast high resolutions and exceptional quality. You can confidently use them for your e-commerce store, social media platforms, or any other marketing channels, knowing they'll catch eyes and captivate potential customers with their impeccable clarity and sharpness.`,
        image: "/result-1",
    },
    {
        headline: "Sell More",
        content: `Beautiful product shoots, carefully crafted by our AI, entice customers towards your product like never before. These visuals have a captivating appeal that grabs attention and ultimately drives your product off the shelves. Elevate your sales strategy and watch your products fly off the virtual and physical shelves, all thanks to our enticing product visuals.`,
        image: "/result-3",
    },
    {
        headline: "Value for Money",
        content: `Invest in our AI-powered product shoots and witness exceptional quality without breaking the bank. Get high-quality product shoots for a fraction of the cost of hiring a professional photographer. Save a significant amount of money and time, allowing you to allocate resources elsewhere while reaping the benefits of top-notch product visuals.`,
        image: "/result-4",
    },
    {
        headline: "Endless Customization",
        content: `Tailor the product shoots generated by our AI to suit your unique preferences and branding. With endless customization options, you have the creative freedom to change the background, tweak shadows, adjust lighting, and more. Personalize each visual to align perfectly with your brand's aesthetic, ensuring your product stands out in a crowded market.`,
        image: "/result-6",
    },
    {
        headline: "Full Ownership",
        content: `Rest assured, you retain complete ownership of the product shoots generated by our AI. Utilize them across your e-commerce store, social media platforms, advertisements, or any marketing medium of your choice without any need for attribution. The visuals are yours to deploy as you see fit, empowering you to showcase your products in the best light without any restrictions or obligations.`,
        image: "/result-5",
    },
];

export function FeaturesSection() {
    return (
        <section
            id="features"
            aria-label="Why should you use our product"
            className="py-10"
        >
            <div className="mx-auto px-4 sm:px-6 lg:px-8">
                <div className="mx-auto text-center">
                    <h1 className="mx-auto max-w-4xl text-4xl font-bold tracking-normal bg-yellow-300 inline-block text-slate-900 sm:text-6xl">
                        Endless Benefits
                    </h1>
                    <p className="mx-auto mt-6 max-w-xl text-lg pb-4 text-slate-700 leading-7">
                        See why you should use our AI Product Shoot generator.
                    </p>
                    <div className="space-y-6">
                        {features.map((feature, index) => {
                            return (
                                <div
                                    key={index}
                                    className="flex md:flex-row flex-col justify-between items-center md:space-y-12"
                                >
                                    {index % 2 == 0 && (
                                        <div className="hidden invisible md:visible flex-col md:flex text-center md:text-left text-slate-900 mr-6">
                                            <div className="max-w-max text-2xl font-bold tracking-normal bg-yellow-300 sm:text-4xl mb-4">
                                                {feature.headline}
                                            </div>
                                            <div className="text-xl max-w-prose">
                                                {feature.content}
                                            </div>
                                        </div>
                                    )}
                                    <Image
                                        alt="Restored photo of my bro"
                                        width={400}
                                        height={400}
                                        src={feature.image + ".jpg"}
                                        className="w-96 h-96 rounded-2xl md:mt-2"
                                    />
                                    {
                                        <div className="md:hidden md:invisible flex-col text-center md:text-left text-slate-900 my-8">
                                            <div className="max-w-max font-display text-2xl font-bold tracking-normal bg-yellow-300 sm:text-4xl mb-4">
                                                {feature.headline}
                                            </div>
                                            <div className="text-xl max-w-prose">
                                                {feature.content}
                                            </div>
                                        </div>
                                    }
                                    {index % 2 == 1 && (
                                        <div className="hidden invisible md:visible flex-col md:flex text-center md:text-left text-slate-900 ml-6">
                                            <div className="max-w-max font-display text-2xl font-bold tracking-normal bg-yellow-300 inline-block sm:text-4xl mb-4">
                                                {feature.headline}
                                            </div>
                                            <div className="text-xl max-w-prose">
                                                {feature.content}
                                            </div>
                                        </div>
                                    )}
                                </div>
                            );
                        })}
                    </div>
                </div>
            </div>
        </section>
    );
}
